/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_g2d_java2d_impl_composite_BlendComposite */

#ifndef _Included_com_g2d_java2d_impl_composite_BlendComposite
#define _Included_com_g2d_java2d_impl_composite_BlendComposite
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_g2d_java2d_impl_composite_BlendComposite
 * Method:    blend_cppImpl
 * Signature: ([I[IIIF)V
 */
JNIEXPORT void JNICALL Java_com_g2d_java2d_impl_composite_BlendComposite_blend_1cppImpl
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint, jfloat);

#ifdef __cplusplus
}
#endif
#endif
