//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellGameEdit.PM {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Config : global::System.Configuration.ApplicationSettingsBase {
        
        private static Config defaultInstance = ((Config)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Config())));
        
        public static Config Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128, 255, 255, 255")]
        public global::System.Drawing.Color MapSrcSelectBackColorL {
            get {
                return ((global::System.Drawing.Color)(this["MapSrcSelectBackColorL"]));
            }
            set {
                this["MapSrcSelectBackColorL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color MapSrcSelectBorderColorL {
            get {
                return ((global::System.Drawing.Color)(this["MapSrcSelectBorderColorL"]));
            }
            set {
                this["MapSrcSelectBorderColorL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color MapSrcSelectBackColorR {
            get {
                return ((global::System.Drawing.Color)(this["MapSrcSelectBackColorR"]));
            }
            set {
                this["MapSrcSelectBackColorR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color MapSrcSelectBorderColorR {
            get {
                return ((global::System.Drawing.Color)(this["MapSrcSelectBorderColorR"]));
            }
            set {
                this["MapSrcSelectBorderColorR"] = value;
            }
        }
    }
}
