/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_g2d_java2d_impl_composite_BlendComposite_BlendingMode */

#ifndef _Included_com_g2d_java2d_impl_composite_BlendComposite_BlendingMode
#define _Included_com_g2d_java2d_impl_composite_BlendComposite_BlendingMode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
