//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellGameEdit {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CellGameEdit.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap CellStudio {
            get {
                object obj = ResourceManager.GetObject("CellStudio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Icon_1 {
            get {
                object obj = ResourceManager.GetObject("Icon_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon IconLord9 {
            get {
                object obj = ResourceManager.GetObject("IconLord9", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image1 {
            get {
                object obj = ResourceManager.GetObject("Image1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image10 {
            get {
                object obj = ResourceManager.GetObject("Image10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image11 {
            get {
                object obj = ResourceManager.GetObject("Image11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image12 {
            get {
                object obj = ResourceManager.GetObject("Image12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image13 {
            get {
                object obj = ResourceManager.GetObject("Image13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image14 {
            get {
                object obj = ResourceManager.GetObject("Image14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image141 {
            get {
                object obj = ResourceManager.GetObject("Image141", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image15 {
            get {
                object obj = ResourceManager.GetObject("Image15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image16 {
            get {
                object obj = ResourceManager.GetObject("Image16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image17 {
            get {
                object obj = ResourceManager.GetObject("Image17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image18 {
            get {
                object obj = ResourceManager.GetObject("Image18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image19 {
            get {
                object obj = ResourceManager.GetObject("Image19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image2 {
            get {
                object obj = ResourceManager.GetObject("Image2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image20 {
            get {
                object obj = ResourceManager.GetObject("Image20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image21 {
            get {
                object obj = ResourceManager.GetObject("Image21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image22 {
            get {
                object obj = ResourceManager.GetObject("Image22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image23 {
            get {
                object obj = ResourceManager.GetObject("Image23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image24 {
            get {
                object obj = ResourceManager.GetObject("Image24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image25 {
            get {
                object obj = ResourceManager.GetObject("Image25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image26 {
            get {
                object obj = ResourceManager.GetObject("Image26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image27 {
            get {
                object obj = ResourceManager.GetObject("Image27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image28 {
            get {
                object obj = ResourceManager.GetObject("Image28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image29 {
            get {
                object obj = ResourceManager.GetObject("Image29", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image3 {
            get {
                object obj = ResourceManager.GetObject("Image3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image30 {
            get {
                object obj = ResourceManager.GetObject("Image30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image31 {
            get {
                object obj = ResourceManager.GetObject("Image31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image32 {
            get {
                object obj = ResourceManager.GetObject("Image32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image33 {
            get {
                object obj = ResourceManager.GetObject("Image33", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image34 {
            get {
                object obj = ResourceManager.GetObject("Image34", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image35 {
            get {
                object obj = ResourceManager.GetObject("Image35", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image36 {
            get {
                object obj = ResourceManager.GetObject("Image36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image37 {
            get {
                object obj = ResourceManager.GetObject("Image37", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image38 {
            get {
                object obj = ResourceManager.GetObject("Image38", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image39 {
            get {
                object obj = ResourceManager.GetObject("Image39", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image4 {
            get {
                object obj = ResourceManager.GetObject("Image4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image40 {
            get {
                object obj = ResourceManager.GetObject("Image40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image41 {
            get {
                object obj = ResourceManager.GetObject("Image41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image42 {
            get {
                object obj = ResourceManager.GetObject("Image42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image43 {
            get {
                object obj = ResourceManager.GetObject("Image43", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image44 {
            get {
                object obj = ResourceManager.GetObject("Image44", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image45 {
            get {
                object obj = ResourceManager.GetObject("Image45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image46 {
            get {
                object obj = ResourceManager.GetObject("Image46", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image47 {
            get {
                object obj = ResourceManager.GetObject("Image47", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image48 {
            get {
                object obj = ResourceManager.GetObject("Image48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image49 {
            get {
                object obj = ResourceManager.GetObject("Image49", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image5 {
            get {
                object obj = ResourceManager.GetObject("Image5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image50 {
            get {
                object obj = ResourceManager.GetObject("Image50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image51 {
            get {
                object obj = ResourceManager.GetObject("Image51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image52 {
            get {
                object obj = ResourceManager.GetObject("Image52", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image53 {
            get {
                object obj = ResourceManager.GetObject("Image53", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image54 {
            get {
                object obj = ResourceManager.GetObject("Image54", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image55 {
            get {
                object obj = ResourceManager.GetObject("Image55", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image56 {
            get {
                object obj = ResourceManager.GetObject("Image56", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image57 {
            get {
                object obj = ResourceManager.GetObject("Image57", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image58 {
            get {
                object obj = ResourceManager.GetObject("Image58", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image59 {
            get {
                object obj = ResourceManager.GetObject("Image59", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image6 {
            get {
                object obj = ResourceManager.GetObject("Image6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image60 {
            get {
                object obj = ResourceManager.GetObject("Image60", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image61 {
            get {
                object obj = ResourceManager.GetObject("Image61", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image62 {
            get {
                object obj = ResourceManager.GetObject("Image62", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image63 {
            get {
                object obj = ResourceManager.GetObject("Image63", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image64 {
            get {
                object obj = ResourceManager.GetObject("Image64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image65 {
            get {
                object obj = ResourceManager.GetObject("Image65", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image66 {
            get {
                object obj = ResourceManager.GetObject("Image66", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image67 {
            get {
                object obj = ResourceManager.GetObject("Image67", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image68 {
            get {
                object obj = ResourceManager.GetObject("Image68", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image69 {
            get {
                object obj = ResourceManager.GetObject("Image69", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image7 {
            get {
                object obj = ResourceManager.GetObject("Image7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image70 {
            get {
                object obj = ResourceManager.GetObject("Image70", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image71 {
            get {
                object obj = ResourceManager.GetObject("Image71", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image72 {
            get {
                object obj = ResourceManager.GetObject("Image72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image73 {
            get {
                object obj = ResourceManager.GetObject("Image73", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image8 {
            get {
                object obj = ResourceManager.GetObject("Image8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image9 {
            get {
                object obj = ResourceManager.GetObject("Image9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageMapClip {
            get {
                object obj = ResourceManager.GetObject("ImageMapClip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ////*世界控制指令*/
        ///WORLD_
        ///
        ////*精灵单位控制指令*/
        ///SPR_SetPos
        ///SPR_Move
        ///
        ////*地图单位控制指令*/
        ///MAP_
        ///
        ////*路点控制指令*/
        ///POINT_SetPos
        ///POINT_Move
        ///
        ////*区域控制指令*/
        ///REGION_SetPos
        ///REGION_Move
        ///REGION_Resize
        /// 的本地化字符串。
        /// </summary>
        internal static string TextCommandList {
            get {
                return ResourceManager.GetString("TextCommandList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ////*世界事件*/
        ///WORLD_Update
        ///
        ////*精灵单位事件类型*/
        ///SPR_Enter
        ///SPR_Leave
        ///SPR_Hold
        ///SPR_Update
        ///
        ////*地图单位事件*/
        ///MAP_Enter
        ///MAP_Leave
        ///MAP_Hold
        ///MAP_Update
        ///
        ////*路点事件*/
        ///POINT_Enter
        ///POINT_Leave
        ///POINT_Hold
        ///POINT_Update
        ///
        ////*区域事件*/
        ///REGION_Enter
        ///REGION_Leave
        ///REGION_Hold
        ///REGION_Update
        ///
        /// 的本地化字符串。
        /// </summary>
        internal static string TextEventList {
            get {
                return ResourceManager.GetString("TextEventList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //--------------------------------------------------------------------------------------------------------------
        /////指令说明
        /////--------------------------------------------------------------------------------------------------------------
        ///格式： 
        /// 所有指令名称由一对&lt;&gt;尖括号包围，#&lt;代表数据块，
        /// 该脚本是对最后生成数据格式的一种约定。
        ///   例如：
        ///     有如下约定
        ///     #&lt;DATA&gt;
        ///          data[&lt;INDEX&gt;] = &lt;DATAS&gt;;
        ///     #&lt;END DATA&gt;
        ///     并且程序里和&lt;DATA&gt;对应的有3个数据块，那么最后生成的数据是
        ///     data[0] = ....;
        ///     data[1] = ....;
        ///     data[2] = ....;
        /////------------------------- [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string TextFileScriptHelp {
            get {
                return ResourceManager.GetString("TextFileScriptHelp", resourceCulture);
            }
        }
    }
}
